### ISSUE TITLE
Port Logstash

### ISSUE THREAD

**Issue by rdrgporto** [consulthys/logstashbeat#1]
Hi,

I have compiled **Logstashbeat** with **Go 1.6.2**. I use **Logstash 2.3.1** which connect to **Elasticsearch 2.3.0**.

When **Logstashbeat** starts, one can see an error about conection with **Logstash** in the log:

```
2016/06/16 07:11:45.057976 logstashbeat.go:136: DBG  Events stats for url: http://localhost:9600
2016/06/16 07:11:45.059671 logstashbeat.go:140: ERR Error reading events stats: Get http://localhost:9600/_node/stats/events: dial tcp 127.0.0.1:9600: getsockopt: connection refused
2016/06/16 07:11:45.059714 logstashbeat.go:158: DBG  JVM stats for url: http://localhost:9600
2016/06/16 07:11:45.060231 logstashbeat.go:162: ERR Error reading JVM stats: Get http://localhost:9600/_node/stats/jvm: dial tcp 127.0.0.1:9600: getsockopt: connection refused
2016/06/16 07:11:45.060279 logstashbeat.go:180: DBG  Process stats for url: http://localhost:9600
2016/06/16 07:11:45.060787 logstashbeat.go:184: ERR Error reading process stats: Get http://localhost:9600/_node/stats/process: dial tcp 127.0.0.1:9600: getsockopt: connection refused
```

Where can I change the Logstash’s port? The default’s port of Logstash is **9600**?

When I execute the previous command:

```
netstat -lanpt | grep LIST | grep java
tcp        0      0 10.80.85.145:9200       0.0.0.0:*               LISTEN      12842/java
tcp        0      0 10.80.85.145:9300       0.0.0.0:*               LISTEN      12842/java
```

Although, I think that these ports are from Elasticsearch.

Thanks in advance,

Regards

**Comment by consulthys** [comment]
This plugin will only work with Logstash 5.0.0-alpha1 and later as the Logstash Monitoring API (listening on port 5600) is only [available since that version](https://www.elastic.co/guide/en/logstash/5.0/alpha1.html).

**Comment by rdrgporto** [comment]
Thank you very much. I will test it with Logstash 5.0.0-alpha1.

**Comment by consulthys** [comment]
My pleasure. You should preferably install the latest 5.0.0.alpha3 version, though.
