### ISSUE TITLE
Cannot use beater.New() as type beat.Creator in argument to beat.Run

### ISSUE THREAD

**Issue by nlowe** [consulthys/logstashbeat#2]
I'm trying to build this for use with `beta-1`. However, i'm getting an error at build time:

``` bash
user@ingest:~/workspace/src/github.com/consulthys/logstashbeat$ make
go build
# github.com/consulthys/logstashbeat
./main.go:12: cannot use beater.New() (type *beater.Logstashbeat) as type beat.Creator in argument to beat.Run
vendor/github.com/elastic/beats/libbeat/scripts/Makefile:73: recipe for target 'logstashbeat' failed
make: *** [logstashbeat] Error 2
```

As far as I can tell, the build process goes like so:

``` bash
make init
make
```

**Comment by consulthys** [comment]
Thanks @nlowe, I think this has to do with Go 1.6 vs 1.7 and the latest updates in the Beats framework. Let me wrap my head around it and come back to you with a solution.

**Comment by consulthys** [comment]
@nlowe which version of Go do you have?

**Comment by nlowe** [comment]
`1.7`, sorry, forgot to mention that.

**Comment by maorshechter** [comment]
hi i also have this problem , itry the make command with go 1.7 and 1.63
any help?

**Comment by consulthys** [comment]
Logstashbeat has been upgraded to work with Go 1.7.1 and Beats 5.
Check it out and try again.
